# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# SPDX-License-Identifier: Zlib
# SPDX-FileCopyrightText: Silicon Laboratories Inc. https://www.silabs.com
---

services:
  broker:
    image: eclipse-mosquitto:1.6.15  # TODO: 2.0.21 needs config files
    ports:
      - '1883:1883'
    command: mosquitto
    logging:
      driver: "none"  # Disables logging for this service
    restart: "no"
    stop_signal: SIGTERM
  zpc:
    image: z-wave-protocol-controller
    build: .
    command: run --mqtt.host=broker --zpc.serial="${ZPC_DEVICE:-/dev/ttyACM0}" ${ZPC_ARGS:--}
    volumes:
      - /dev/pts:/dev/pts
    devices:
      - ${ZPC_DEVICE:-/dev/ttyACM0}:/dev/ttyUSB0
    depends_on:
      broker:
        condition: service_started
    environment:
      ZPC_ARGS: "--"
