[package]
name = "unify_portable_gui"
version = "0.0.1"
edition = "2021"
authors = ["Sergiy Pastukh <sepastuk@silabs.com>"]
build = "build.rs"
license = "Copyright 2022 Silicon Laboratories Inc. www.silabs.com\nThe licensor of this software is Silicon Laboratories Inc.\nYour use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement.\nThis software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code."
description = "The Unify Portable GUI is the graphical interface for starting, stopping and viewing the status of the Unify portable runtime. It makes use of the unify-portable-core library."

[build-dependencies]
tauri-build = { version = "1.0.0-rc.12", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
local_ipaddress = "0.1.3"
file-matcher = "0.7.0"
tauri = { version = "1.0.0-rc.14", features = ["api-all"] }
unify_portable_core = { path = "../../unify_portable_core" }
exitcode = "1.1.2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
