add_subdirectory(crc16_ccitt)
add_subdirectory(common)
add_subdirectory(config)
add_subdirectory(datastore)
add_subdirectory(attribute_store)
add_subdirectory(smartstart)
add_subdirectory(mqtt)
add_subdirectory(attribute_resolver)
add_subdirectory(attribute_timeouts)
add_subdirectory(platform)
add_subdirectory(state_machine)
add_subdirectory(main)

add_subdirectory(zwave_api)
add_subdirectory(utils)

add_subdirectory(zwave)
add_subdirectory(network_manager)

# Add all component libraries
set(COMPONENT_EVENT_BASE_STEP 0x40)
set(COMPONENT_EVENT_BASE 0x00010000)

set(COMPONENT_ATTRIBUTE_BASE_STEP 0x80)
set(COMPONENT_ATTRIBUTE_BASE 0x00010000)

add_subdirectory(component_connector)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(system)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(granted_keys_resolver)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(node_info_resolver)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(device_interviewer)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(ota)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(mqtt_api)
math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(network_monitor)
add_subdirectory(discovery)
add_subdirectory(security)
add_subdirectory(jamming_detection)

math(EXPR COMPONENT_EVENT_BASE "${COMPONENT_EVENT_BASE} + ${COMPONENT_EVENT_BASE_STEP}")
math(EXPR COMPONENT_ATTRIBUTE_BASE "${COMPONENT_ATTRIBUTE_BASE} + ${COMPONENT_ATTRIBUTE_BASE_STEP}")
add_subdirectory(command_classes)
add_subdirectory(zwave_command_class_manager)
