[package]
name = "unify_portable_core"
version = "0.0.2"
edition = "2021"
authors = ["Thomas Bowley <thomas.bowley@silabs.com>"]
license = "Copyright 2022 Silicon Laboratories Inc. www.silabs.com\nThe licensor of this software is Silicon Laboratories Inc.\nYour use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement.\nThis software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code."
description = "The Unify Portable Core library contains the basic functions needed for running the Unify Framework in a portable runtime."
include = ["../resources"]

[dependencies]
duct = "0.13.5"
local_ipaddress = "0.1.3"
serde_json = "1.0.81"
file-matcher = "0.7.0"
port-selector = "0.1.6"
regex = "1.6.0"
lazy_static = "1.4.0"
bimap = "0.6.3"
