/******************************************************************************
 * # License
 * <b>Copyright 2024 Silicon Laboratories Inc. www.silabs.com</b>
 ******************************************************************************
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 *****************************************************************************/

/**
 * @defgroup zpc_mqtt ZPC MQTT
 * @ingroup zpc_components
 * @brief Component interfacing between ZPC states/commands and MQTT
 *
 * This component contains the various ZPC MQTT interfaces, that do not exist
 * in DotDot, and thus is not autogenerated as the DotDot cluster mappers.
 *
 * @{
 */

#ifndef ZPC_MQTT_H
#define ZPC_MQTT_H

// Other components
#include "zpc_mqtt_definitions.hpp"  // mqtt_command_callback

// Cpp
#include <string>

// ZPC
#include "attribute_store.h"  // attribute_store_type_t

namespace zpc_mqtt
{

#ifdef __cplusplus
    extern "C" {
#endif

    /**
     * @brief Register an attribute type for the ZPC MQTT component.
     *
     * Not all attribute are supported. Attributes that has the following storage types
     * are NOT supported:
     *
     * - EMPTY_STORAGE_TYPE
     *
     * - INVALID_STORAGE_TYPE
     *
     * - UNKNOWN_STORAGE_TYPE
     *
     * - FIXED_SIZE_STRUCT_STORAGE_TYPE
     *
     * @param attribute_type The attribute type to register. Not all types are supported see above.
     * @param command_class_name The name of the command class
     * @param attribute_name The name of the attribute
     *
     * @return sl_status_t SL_STATUS_OK if successful, SL_STATUS_FAIL otherwise
     */
    sl_status_t register_attribute(attribute_store_type_t attribute_type, const std::string &command_class_name, const std::string &attribute_name);

    sl_status_t publish_report(const char *topic, const char *message, size_t message_length, bool retain = true);

    /**
     * @brief Register a command for the ZPC MQTT component.
     *
     * @param command_class_name The name of the command class
     * @param callback The callback to call when a command for this command class is received
     *
     * @return sl_status_t SL_STATUS_OK if successful, SL_STATUS_FAIL otherwise
     */
    sl_status_t register_command(const std::string &command_class_name, const mqtt_command_callback &callback);

    /**
     * @brief Register a value transformation for a given attribute type
     *
     * Some attributes need transformation into string before being published.
     * Use this function to register a function that will be applied before publishing
     * the value.
     *
     * We don't use template here because it cause a lot of issues with the C linkage,
     * and the way this namespace is implemented. Instead the function is responsible
     * to get the value if the given node and state and transform it to a string.
     *
     * @param attribute_type The attribute type to register the transformation for
     * @param encoder The encoder to use to transform the value to a string
     *
     */
    void register_value_transformation(attribute_store_type_t attribute_type, const mqtt_value_encoder &encoder);

#ifdef __cplusplus
    }
#endif

}  // namespace zpc_mqtt

#endif  // ZPC_MQTT_H
/** @} end zpc_mqtt */
