name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Build Docker image from sources
      run: docker build .
