# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: Build in rootfs for arch

on:  # yamllint disable-line rule:truthy
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch:
          - amd64
          # - armhf # TODO Enable when supported
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - id: describe
        name: Describe HEAD
        run: >-
          echo "describe=$(git describe --tags --always || echo 0)"
          | tee $GITHUB_OUTPUT
      - id: build-docs
      - name: Build documentation once
        run: |
          apt-get install -y install make
          ./helper.mk docs
  deploy:
    needs: build-docs
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: 'github-pages'
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
