# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: Test release

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: clone-private
        run: >
          git clone --depth 1
          --branch z-wave/init/main
          https://${{ secrets.GH_UNIFY_ACCESS_TOKEN }}@github.com/SiliconLabs/UnifySDK_test.git      
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - id: describe
        name: Describe HEAD
        run: >
          echo "describe=$(git describe --tags --always || echo 0)"
          | tee $GITHUB_OUTPUT
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_UNIFY_ACCESS_TOKEN }}
        run: >
          gh release create
          ${{ steps.describe.outputs.describe }}
